In [1]:
import os
import pandas as pd
import joblib
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

## Registry Model

In [2]:
# Path Folder
data_dir = os.path.join('..', 'dataset', 'engineered')
models_dir = os.path.join('..', 'models')

# Path Data Uji (Test Set)
path_test_ec = os.path.join(data_dir, 'ecoli_test_engineered.csv')
path_test_gl = os.path.join(data_dir, 'glass_test_engineered.csv')
path_test_th = os.path.join(data_dir, 'thyroid_test_engineered.csv')

## Automasi Evaluasi

In [3]:
def evaluate_models(dataset_name, test_data_path, model_names):
    print(f"=== Evaluasi Model untuk Dataset: {dataset_name.upper()} ===")
    
    df_test = pd.read_csv(test_data_path)
    X_test = df_test.drop(columns=['label_encoded'])
    y_test = df_test['label_encoded']
    
    results = []
    
    for model_name in model_names:
        model_filename = f"{dataset_name}_{model_name.lower()}.pkl"
        model_path = os.path.join(models_dir, model_filename)
        
        model = joblib.load(model_path)
        
        y_pred = model.predict(X_test)
        
        acc = accuracy_score(y_test, y_pred)
        prec = precision_score(y_test, y_pred, average='weighted', zero_division=0)
        rec = recall_score(y_test, y_pred, average='weighted', zero_division=0)
        f1 = f1_score(y_test, y_pred, average='weighted', zero_division=0)
        
        results.append({
            'Dataset': dataset_name.capitalize(),
            'Model': model_name,
            'Accuracy': round(acc, 4),
            'Precision': round(prec, 4),
            'Recall': round(rec, 4),
            'F1-Score': round(f1, 4)
        })
        
    df_results = pd.DataFrame(results)
    return df_results

print("[2] Fungsi evaluasi berhasil dibuat.")

[2] Fungsi evaluasi berhasil dibuat.

## Evaluasi Model `ecoli`

In [4]:
algorithms = ['Naive_Bayes', 'KNN', 'Decision_Tree']

df_eval_ec = evaluate_models('ecoli', path_test_ec, algorithms)

print("\n--- Hasil Evaluasi ECOLI ---")
display(df_eval_ec)

=== Evaluasi Model untuk Dataset: ECOLI ===

--- Hasil Evaluasi ECOLI ---

  Dataset          Model  Accuracy  Precision  Recall  F1-Score
0   Ecoli    Naive_Bayes    0.8088     0.8798  0.8088    0.7943
1   Ecoli            KNN    0.8382     0.8600  0.8382    0.8334
2   Ecoli  Decision_Tree    0.7500     0.8793  0.7500    0.7880

## Evaluasi Model `glass`

In [5]:
df_eval_gl = evaluate_models('glass', path_test_gl, algorithms)

print("\n--- Hasil Evaluasi GLASS ---")
display(df_eval_gl)

=== Evaluasi Model untuk Dataset: GLASS ===

--- Hasil Evaluasi GLASS ---

  Dataset          Model  Accuracy  Precision  Recall  F1-Score
0   Glass    Naive_Bayes    0.5116     0.6016  0.5116    0.4782
1   Glass            KNN    0.7674     0.7844  0.7674    0.7697
2   Glass  Decision_Tree    0.7209     0.7248  0.7209    0.7150

# Evauasi Model `thyroid`

In [6]:
df_eval_th = evaluate_models('thyroid', path_test_th, algorithms)

print("\n--- Hasil Evaluasi THYROID ---")
display(df_eval_th)

=== Evaluasi Model untuk Dataset: THYROID ===

--- Hasil Evaluasi THYROID ---

   Dataset          Model  Accuracy  Precision  Recall  F1-Score
0  Thyroid    Naive_Bayes    0.1711     0.9261  0.1711    0.1930
1  Thyroid            KNN    0.8794     0.9359  0.8794    0.9014
2  Thyroid  Decision_Tree    0.9972     0.9973  0.9972    0.9972

## Penggabungan Evaluasi Model

In [7]:
df_all_results = pd.concat([df_eval_ec, df_eval_gl, df_eval_th], ignore_index=True)

reports_dir = os.path.join('..', 'reports')
os.makedirs(reports_dir, exist_ok=True)
df_all_results.to_csv(os.path.join(reports_dir, 'all_models_evaluation.csv'), index=False)

print("\n=== RINGKASAN EVALUASI SELURUH MODEL ===")
print("File ringkasan juga telah disimpan di: reports/all_models_evaluation.csv\n")
display(df_all_results)

=== RINGKASAN EVALUASI SELURUH MODEL ===
File ringkasan juga telah disimpan di: reports/all_models_evaluation.csv

   Dataset          Model  Accuracy  Precision  Recall  F1-Score
0    Ecoli    Naive_Bayes    0.8088     0.8798  0.8088    0.7943
1    Ecoli            KNN    0.8382     0.8600  0.8382    0.8334
2    Ecoli  Decision_Tree    0.7500     0.8793  0.7500    0.7880
3    Glass    Naive_Bayes    0.5116     0.6016  0.5116    0.4782
4    Glass            KNN    0.7674     0.7844  0.7674    0.7697
5    Glass  Decision_Tree    0.7209     0.7248  0.7209    0.7150
6  Thyroid    Naive_Bayes    0.1711     0.9261  0.1711    0.1930
7  Thyroid            KNN    0.8794     0.9359  0.8794    0.9014
8  Thyroid  Decision_Tree    0.9972     0.9973  0.9972    0.9972